### PR TITLE
Support multiple subnets

### PR DESCRIPTION
**Pull request by ryanwohara**

### CODE REVIEW

**Review by nsmith5 — CHANGES_REQUESTED** [review]
I think this can be better from a backwards compatibility and clarity perspective:

- The variable name `subnet` doesn't reflect that its now a list of subnets
- The change in type from string to list(string) will break updates (users need to modify tfvars even if they haven't added new subnets)

**Comment by ryanwohara** [comment]
I'm also worried about the backwards compatibility for this. That's good feedback, I'll have to think this over further.

**Review by lloydChris — APPROVED** [review]
Looks good

Nit: merging the commits would make a nice clean history

**Review by soulchips — APPROVED** [review]

**Review by nsmith5 — APPROVED** [review]
Looks good! 🚀

**Pull request merged**
