### PR TITLE
[No JIRA] force_destroy was not configured for gke buckets

### PR DESCRIPTION
**Pull request by soulchips**
GCP buckets did not have the option to toggle force_destroy

Also an update to the S3 bucket tagging to reflect the state of force_destroy

### CODE REVIEW

**Review by robinsturmeit — APPROVED** [review]
Good catch!

**Review by lloydChris — CHANGES_REQUESTED** [review]
Nice.  Add this to the vars template file as well, like is done for EKS: https://github.com/CircleCI-Public/server-terraform/blob/main/eks/terraform.tfvars.template#L13

**Comment by soulchips** [comment]
good callout @lloydChris

**Review by yugesh84 — APPROVED** [review]
LGTM - nice catch.

**Review by lloydChris — APPROVED** [review]

**Pull request merged**
